<<<<<<< HEAD
# Generated by Django 3.1.4 on 2021-01-03 03:50
=======
# Generated by Django 3.1.4 on 2021-01-01 17:10
>>>>>>> ca2b5b0 (Add: Flight 앱 생성, 카테고리 API 구현, 항공권 리스트 구현, 유닛 테스트 완료)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('logo_url', models.URLField(max_length=2000)),
            ],
            options={
                'db_table': 'airlines',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('code', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'airports',
            },
        ),
        migrations.CreateModel(
            name='DetailedPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fuel_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_and_utility_charge', models.DecimalField(decimal_places=2, default=8000, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'detailed_prices',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=45)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('departure_date', models.DateField()),
                ('arrival_date', models.DateField()),
                ('remain_seat', models.IntegerField(default=9)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'flights',
            },
        ),
        migrations.CreateModel(
            name='FlightBookingInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=45)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flight')),
            ],
            options={
                'db_table': 'flight_booking_informations',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'genders',
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'nationalities',
            },
        ),
        migrations.CreateModel(
            name='PassengerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'passenger_types',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardholder_name', models.CharField(max_length=45)),
                ('card_company', models.CharField(max_length=45)),
                ('card_number', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('installment_month', models.IntegerField()),
                ('card_password', models.IntegerField()),
                ('birth_date', models.IntegerField()),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'regions',
            },
        ),
        migrations.CreateModel(
            name='SeatClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'seat_classes',
            },
        ),
        migrations.CreateModel(
            name='PassengerInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('birth_date', models.DateField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.gender')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.nationality')),
            ],
            options={
                'db_table': 'passenger_informations',
            },
        ),
        migrations.CreateModel(
            name='FlightPassenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('flight_booking_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.flightbookinginformation')),
                ('passenger_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.passengertype')),
            ],
            options={
                'db_table': 'flight_passengers',
            },
        ),
        migrations.AddField(
            model_name='flightbookinginformation',
            name='passenger_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.passengerinformation'),
        ),
        migrations.AddField(
            model_name='flightbookinginformation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.payment'),
        ),
    ]
