<<<<<<< HEAD:flight/migrations/0002_auto_20210103_1250.py
# Generated by Django 3.1.4 on 2021-01-03 03:50
=======
# Generated by Django 3.1.4 on 2021-01-01 17:10
>>>>>>> ca2b5b0 (Add: Flight 앱 생성, 카테고리 API 구현, 항공권 리스트 구현, 유닛 테스트 완료):flight/migrations/0002_auto_20210102_0210.py

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbookinginformation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='flight',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.airline'),
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival', to='flight.airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure', to='flight.airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='detailed_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.detailedprice'),
        ),
        migrations.AddField(
            model_name='flight',
            name='seat_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.seatclass'),
        ),
        migrations.AddField(
            model_name='airport',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.region'),
        ),
    ]
