# Generated by Django 3.1.4 on 2020-12-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20201230_1849'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='detailedprice',
            table='detailed_prices',
        ),
    ]
