# Generated by Django 3.1.4 on 2021-01-26 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_auto_20210126_1211'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='departuretimerange',
            table='departure_time_ranges',
        ),
    ]
