# Generated by Django 3.1.4 on 2021-01-03 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0001_initial'),
        ('accommodation', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoupon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='theme',
            name='accommodation_theme',
            field=models.ManyToManyField(through='accommodation.AccommodationTheme', to='accommodation.Accommodation'),
        ),
        migrations.AddField(
            model_name='roomtypeamenity',
            name='room_amenity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accommodation.roomamenity'),
        ),
        migrations.AddField(
            model_name='roomtypeamenity',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.roomtype'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.accommodation'),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='room_type_amenity',
            field=models.ManyToManyField(through='accommodation.RoomTypeAmenity', to='accommodation.RoomAmenity'),
        ),
        migrations.AddField(
            model_name='review',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.accommodation'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.accommodation'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='accommodation_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.accommodationpayment'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='age_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.agegroup'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.gender'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='travel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.traveltype'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='user_coupon',
            field=models.ManyToManyField(through='accommodation.UserCoupon', to='user.User'),
        ),
        migrations.AddField(
            model_name='accommodationtheme',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.accommodation'),
        ),
        migrations.AddField(
            model_name='accommodationtheme',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.theme'),
        ),
        migrations.AddField(
            model_name='accommodationservice',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.accommodation'),
        ),
        migrations.AddField(
            model_name='accommodationservice',
            name='free_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.freeservice'),
        ),
        migrations.AddField(
            model_name='accommodationroom',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.accommodation'),
        ),
        migrations.AddField(
            model_name='accommodationroom',
            name='general_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.generalroom'),
        ),
        migrations.AddField(
            model_name='accommodationpayment',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accommodation.paymentmethod'),
        ),
        migrations.AddField(
            model_name='accommodationimage',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.accommodation'),
        ),
        migrations.AddField(
            model_name='accommodationfacility',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.accommodation'),
        ),
        migrations.AddField(
            model_name='accommodationfacility',
            name='shared_facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.sharedfacility'),
        ),
        migrations.AddField(
            model_name='accommodationdormitory',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.accommodation'),
        ),
        migrations.AddField(
            model_name='accommodationdormitory',
            name='dormitory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.dormitory'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='accommodation_dormitory',
            field=models.ManyToManyField(through='accommodation.AccommodationDormitory', to='accommodation.Dormitory'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='accommodation_facility',
            field=models.ManyToManyField(through='accommodation.AccommodationFacility', to='accommodation.SharedFacility'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='accommodation_room',
            field=models.ManyToManyField(through='accommodation.AccommodationRoom', to='accommodation.GeneralRoom'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='accommodation_service',
            field=models.ManyToManyField(through='accommodation.AccommodationService', to='accommodation.FreeService'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accommodation.host'),
        ),
    ]
